algo = input('Digite algo: ')
print('O tipo do valor digitado é:', type(algo))
print('O valor é número?', algo.isnumeric())
print('O valor é letra?', algo.isalpha())
print('O valor é alfanumérico?', algo.isalnum())
print('O valor está maiúsculo?', algo.isupper())
print('O valor está minúsculo?', algo.islower())
print('O valor tem somente espaço?', algo.isspace())
print('O valor está capitalizada?', algo.istitle())
